More additions and corrections for product/community build.
Signed-off-by: John Krug <john.krug@suse.com>

diff --git a/bin/switch-prod-comm b/bin/switch-prod-comm
--- a/bin/switch-prod-comm
+++ b/bin/switch-prod-comm
@@ -2,6 +2,21 @@
 
 # Switch version yaml files between community and product versions
 
+function px_error () {
+  echo "Error: $1"
+  exit 1
+}
+
+
+function fetch_versions_list () {
+  local versions
+  versions=$(ls -1 "$docs_root")
+  echo "$versions"
+}
+
+
+# main
+
 target_version="$1"
 
 if [ -z "$target_version" ]; then
@@ -9,25 +24,16 @@ if [ -z "$target_version" ]; then
   exit 1
 fi
 
+# shellcheck disable=SC2086,SC2046
 docs_root="$(realpath $(dirname $0)/../docs)"
 echo "Docs root: $docs_root"
 
-function fetch_versions_list () {
-  local versions=$(ls -1 $docs_root)
-  echo "$versions"
-}
-
 for version in $(fetch_versions_list); do
   echo "Processing $version"
-  cd "$docs_root/$version"
-  if [ $? -ne 0 ]; then
-    echo "Error: $docs_root/$version not found"
-    exit 1
-  fi
+  cd "$docs_root/$version" || px_error "failed to cd to $docs_root/$version"
   if [ -f antora-yml/antora-"$target_version".yml ]; then
-    ln -sf antora-yml/antora-"$target_version".yml antora.yml
-    if [ $? -eq 0 ]; then
-      echo "Switched to antora.yml -> antora-yml/antora-$target_version.yml"
+    if ln -sf antora-yml/antora-"$target_version".yml antora.yml; then
+      echo "Switched to $target_version : antora.yml -> antora-yml/antora-$target_version.yml"
     else
       echo "Error: failed to switch to antora-yml/antora-$target_version.yml"
       exit 1
